name: Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v2
      - name: Build
        run: cargo build --release --all-features

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v2
      - name: Test
        run: cargo test

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v2
      - name: Clippy
        run: cargo clippy -- -D warnings

# TODO: deploy to crates.io on new release
#  publish:
#    runs-on: ubuntu-latest
#    needs: [build, test, clippy]
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions-rs/toolchain@v2
#      - run: cargo publish